CREATE OR REPLACE PROCEDURE KELILING_LINGKARAN AS
V_PHI FLOAT(5) :=3.14;
V_JARI NUMBER(2) :=5;
V_KELILING FLOAT;
BEGIN
V_KELILING :=V_PHI*V_JARI*2;
DBMS_OUTPUT.PUT_LINE('LUAS LINGKARAN ADALAH='||' '||V_KELILING);
END;
/
