CREATE OR REPLACE PROCEDURE KELILING_SEGITIGA AS
V_SISI1 NUMBER(5) :=6;
V_SISI2 NUMBER(5) :=7;
V_SISI3 NUMBER(5) :=5;
V_KELILING NUMBER(5);
BEGIN
V_KELILING :=V_SISI1+V_SISI2+V_SISI3;
DBMS_OUTPUT.PUT_LINE('KELILING SEGITIGA ADALAH='||' '||V_KELILING);
END;
/
