CREATE OR REPLACE PROCEDURE LUAS_SEGITIGA AS
V_TINGGI NUMBER(5) :=6;
V_ALAS NUMBER(5) :=7;
V_LUAS NUMBER(5);
BEGIN
V_LUAS :=V_ALAS*V_TINGGI/2;
DBMS_OUTPUT.PUT_LINE(‘LUAS SEGITIGA ADALAH='||' '||V_LUAS);
END;
/
