CREATE OR REPLACE PROCEDURE SOALNO4 IS
 CURSOR CUR_SOALNO4 IS SELECT EMPLOYEE_ID, FIRST_NAME, E.DEPARTMENT_ID, E.JOB_ID, SALARY, COMMISSION_PCT
 FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
	 E.JOB_ID = J.JOB_ID AND
	 E.JOB_ID LIKE '%REP%' AND E.DEPARTMENT_ID IN (80, 85);
V_CUR_SOALNO4_REC CUR_SOALNO4%ROWTYPE;
V_TOTAL NUMBER;
BEGIN
 OPEN CUR_SOALNO4;
 LOOP
  FETCH CUR_SOALNO4 INTO V_CUR_SOALNO4_REC;
  V_TOTAL := V_CUR_SOALNO4_REC.SALARY + (V_CUR_SOALNO4_REC.SALARY * NVL(V_CUR_SOALNO4_REC.COMMISSION_PCT,0));
  DBMS_OUTPUT.PUT_LINE ('ID : ' || V_CUR_SOALNO4_REC.EMPLOYEE_ID|| ' , NAMA : ' || V_CUR_SOALNO4_REC.FIRST_NAME || ' ,DEPT : '|| V_CUR_SOALNO4_REC.DEPARTMENT_ID || ' , JOB : ' || V_CUR_SOALNO4_REC.JOB_ID ||' ,GAJI POKOK ' || V_CUR_SOALNO4_REC.SALARY||
' , TOTAL GAJI ' || V_TOTAL);
 EXIT WHEN CUR_SOALNO4%NOTFOUND;
 END LOOP;
 CLOSE CUR_SOALNO4;
END;
/