CREATE OR REPLACE PROCEDURE SOAL5 IS
   CURSOR CUR_SOAL5 IS SELECT EMPLOYEE_ID, FIRST_NAME, CITY
   FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
   WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID;
V_CUR_SOAL5_REC CUR_SOAL5%ROWTYPE;
V_STATUS VARCHAR2 (10);
BEGIN
  OPEN CUR_SOAL5;
  LOOP
      FETCH CUR_SOAL5 INTO V_CUR_SOAL5_REC;
        IF (V_CUR_SOAL5_REC.EMPLOYEE_ID MOD 2 = 0 ) THEN
           V_STATUS := 'GENAP';
        ELSE
           V_STATUS := 'GANJIL';
        END IF;
      DBMS_OUTPUT.PUT_LINE('ID : ' || V_CUR_SOAL5_REC.EMPLOYEE_ID ||' '||', NAMA: ' ||V_CUR_SOAL5_REC.FIRST_NAME||' '||', KOTA : '|| V_CUR_SOAL5_REC.CITY||' '||' STATUS : ' || V_STATUS);
     EXIT WHEN CUR_SOAL5%NOTFOUND OR CUR_SOAL5%ROWCOUNT >=10 ;
     END LOOP;
     CLOSE CUR_SOAL5;
END;
/